[package]
name = "minienvs"
version = "0.1.1"
entrypoint = "minienvs.typ"
exclude = ["sandbox.typ", "*.pdf", "assets/*"]
authors = ["Daniel Csillag"]
license = "MIT"
description = "Theorem environments with minimal fuss"
repository = "https://github.com/dccsillag/minienvs.typ"